GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOGET=$(GOCMD) GOGET

BIN_NAME=Pixie-0.2

BIN_PATH=./bin/$(BIN_NAME)
SOURCE_PATH=./cmd/bot/main.go

build:
	$(GOBUILD) -o $(BIN_PATH) $(SOURCE_PATH)